[WMI, Dynamic, Provider("WMIProv"),
 guid("{DE81837E-BD78-4EC8-ABA8-89B7D026C1CF}"),
 localeid(0x409),
 WmiExpense(1),
 Description("Qualcomm Device Information")]
class QualcommDeviceInformation
{
   [key, read]
   string   InstanceName;           // Instance name returned from WMI
   
   [read]
   boolean  Active;

   [WmiDataId(1),
    read,
    Description("Number of Data Blocks.")
   ]
   uint32   DataBlocks;
   
   [WmiDataId(2),
    read,
    Description("Qualcomm Model ID.")
   ]
   string   ModelId;

   [WmiDataId(3),
    read,
    Description("Qualcomm Firmware Revision.")
   ]
   string   FirmwareRevision;

   [WmiDataId(4),
    read,
    Description("Qualcomm MEID.")   ]
   string   MEID;

   [WmiDataId(5),
    read,
    Description("Qualcomm ESN.")
   ]
   string   ESN;

   [WmiDataId(6),
    read,
    Description("Qualcomm IMEI.")
   ]
   string   IMEI;

   [WmiDataId(7),
    read,
    Description("Qualcomm IMSI.")
   ]
   string   IMSI;

   [WmiDataId(8),
    read,
    Description("Qualcomm MIN.")
   ]
   string   MIN;

   [WmiDataId(9),
    read,
    Description("Qualcomm MDN.")
   ]
   string   MDN;

   [WmiDataId(10),
    read,
    Description("Qualcomm Manufacturer.")
   ]
   string   Manufacturer;

   [WmiDataId(11),
    read,
    Description("Qualcomm Hardware Revision.")
   ]
   string   HardwareRevision;
   
};

